#!/usr/bin/env bash
# Turns on remote push in a Capacitor iOS project generated by `npx cap add ios`.
# Safe to run more than once. Run after `npx cap add ios` / `npx cap sync ios`.
#   1. App.entitlements with aps-environment (production by default; APS_ENVIRONMENT=development to override)
#   2. CODE_SIGN_ENTITLEMENTS on the App target's build configurations
#   3. AppDelegate methods that hand the APNs device token to @capacitor/push-notifications
set -euo pipefail
IOS_APP_DIR="${1:-ios/App}"
APP_DIR="$IOS_APP_DIR/App"
PBX="$IOS_APP_DIR/App.xcodeproj/project.pbxproj"
DELEGATE="$APP_DIR/AppDelegate.swift"
ENT="$APP_DIR/App.entitlements"
APS_ENV="${APS_ENVIRONMENT:-production}"

[ -f "$PBX" ] || { echo "ios-enable-push: $PBX not found" >&2; exit 1; }
[ -f "$DELEGATE" ] || { echo "ios-enable-push: $DELEGATE not found" >&2; exit 1; }

cat > "$ENT" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>${APS_ENV}</string>
</dict>
</plist>
PLIST

if ! grep -q "CODE_SIGN_ENTITLEMENTS" "$PBX"; then
  # Only the App target's configurations carry PRODUCT_BUNDLE_IDENTIFIER.
  # perl, not sed: Codemagic's macOS sed does not expand \n in replacements.
  perl -pi -e 's/^(\s*)PRODUCT_BUNDLE_IDENTIFIER = /$1CODE_SIGN_ENTITLEMENTS = App\/App.entitlements;\n$1PRODUCT_BUNDLE_IDENTIFIER = /' "$PBX"
fi
COUNT=$(grep -c "CODE_SIGN_ENTITLEMENTS = App/App.entitlements;" "$PBX" || true)
[ "$COUNT" -ge 1 ] || { echo "ios-enable-push: could not set CODE_SIGN_ENTITLEMENTS" >&2; exit 1; }

if ! grep -q "capacitorDidRegisterForRemoteNotifications" "$DELEGATE"; then
  cat >> "$DELEGATE" <<'SWIFT'

// Remote push: hand the APNs token to @capacitor/push-notifications.
extension AppDelegate {
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
    }
}
SWIFT
fi
echo "ios-enable-push: aps-environment=$APS_ENV, entitlements set on $COUNT configuration(s), AppDelegate wired."
