export const APP_NAME = 'MotoCrew'
export const VERSION_LABEL = 'v0.3-map'
export const BUILD_TARGET = 'web'
export const DEFAULT_MARKET = 'Local Pilot'
export const APP_TAGLINE = 'Plan the ride. Ride with the pack.'
export const FEEDBACK_EMAIL = 'feedback@macksims.com'
export const CONCEPT_LINEAGE = 'MotoCrew is the current branding of the Throttle / ThrottleLink concept.'
export const SAFETY_NOTICE = 'Do not use this app while riding. Set everything up before kickstands-up. Eyes on the road.'
export const DEMO_NOTICE =
  'Ride planning and checklists work on this device. Live GPS tracking, pack voice, and emergency dispatch are not connected yet.'
